repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: check python import sorting
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: check python code style
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  #- repo: local
  #  hooks:
  #    - id: pytest
  #      name: pytest
  #      entry: uv
  #      language: system
  #      pass_filenames: false
  #      args: ["run", "pytest"]
